"""Add 'leave_allocation' table

Revision ID: 0e920f4f1e01
Revises: f467fb472abf
Create Date: 2024-07-27 15:36:45.744027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e920f4f1e01'
down_revision = 'f467fb472abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empid', sa.Integer(), nullable=False),
    sa.Column('year_start', sa.Date(), nullable=False),
    sa.Column('year_end', sa.Date(), nullable=False),
    sa.Column('casual', sa.Integer(), nullable=False),
    sa.Column('medical', sa.Integer(), nullable=False),
    sa.Column('earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empid'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_allocation')
    # ### end Alembic commands ###
