"""Rename column names in 'leave_available' table

Revision ID: 119d2fcd0d9f
Revises: 3bea1221d5b2
Create Date: 2024-07-28 15:01:29.584475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119d2fcd0d9f'
down_revision = '3bea1221d5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_available', schema=None) as batch_op:
        batch_op.alter_column('year_start', new_column_name='fiscal_year_start_date')
        batch_op.alter_column('year_end', new_column_name='fiscal_year_end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_available', schema=None) as batch_op:
        batch_op.alter_column('fiscal_year_start_date', new_column_name='year_start')
        batch_op.alter_column('fiscal_year_end_date', new_column_name='year_end')

    # ### end Alembic commands ###
