"""Rename column names in 'leave_allocation' table

Revision ID: 3bea1221d5b2
Revises: a12cf9716f7e
Create Date: 2024-07-28 14:58:15.604647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bea1221d5b2'
down_revision = 'a12cf9716f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fiscal_year_start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fiscal_year_end_date', sa.Date(), nullable=False))
        batch_op.drop_column('year_end')
        batch_op.drop_column('year_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_allocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_start', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('year_end', sa.DATE(), nullable=False))
        batch_op.drop_column('fiscal_year_end_date')
        batch_op.drop_column('fiscal_year_start_date')

    # ### end Alembic commands ###
